Remove non-existent normalize_score import
Removed incorrect import of normalize_score from normalization module.
This function doesn't exist and isn't used anywhere in the codebase.

Available normalization functions are:
- normalize_minmax
- normalize_by_tier
- normalize_log10
- normalize_log10_by_tier

Fixes: ImportError: cannot import name 'normalize_score'